# Generated by Django 5.1 on 2024-09-01 12:02

import django.contrib.gis.db.models.fields
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('geoapp', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='featurecollection',
            name='features',
        ),
        migrations.AddField(
            model_name='featurecollection',
            name='crs',
            field=models.CharField(default='def', max_length=100),
            preserve_default=False,
        ),
        migrations.CreateModel(
            name='Feature',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('geometry', django.contrib.gis.db.models.fields.MultiPolygonField(srid=4326)),
                ('feature_collection', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='features', to='geoapp.featurecollection')),
            ],
        ),
    ]
