# Generated by Django 5.1 on 2024-09-01 12:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('geoapp', '0002_remove_featurecollection_features_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='featurecollection',
            name='crs',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='featurecollection',
            name='name',
            field=models.CharField(max_length=255),
        ),
    ]
