# Generated by Django 5.1 on 2024-09-02 07:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('geoapp', '0003_alter_featurecollection_crs_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='feature',
            name='properties',
            field=models.JSONField(default=None),
            preserve_default=False,
        ),
    ]
