# Generated by Django 5.1 on 2024-09-02 08:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('geoapp', '0004_feature_properties'),
    ]

    operations = [
        migrations.AddField(
            model_name='feature',
            name='type',
            field=models.CharField(default='Feature', max_length=255),
        ),
    ]
