
name: Django Test via Docker# Name of the workflow

on: [push]  # Trigger the workflow on a push event to any branch in the repo

jobs:
    test:  # Define a job named 'test'
        name: Run unit tests  # A more descriptive name for the job
        runs-on: ubuntu-22.04  # Specify the runner environment (Ubuntu 22.04)

        steps:  # Steps to be run as part of this job
            - name: Login to Docker Hub  # Step 1: Log in to Docker Hub
              uses: docker/login-action@v1  # Use the docker/login-action to log in to Docker Hub
              with:
                username: ${{ secrets.DOCKERHUB_USERNAME }}  # Use the stored Docker Hub username
                password: ${{ secrets.DOCKERHUB_TOKEN }}  # Use the stored Docker Hub token for authentication

            - name: Checkout  # Step 2: Checkout the repository code
              uses: actions/checkout@v2  # Use the checkout action to checkout the code

            - name: Test  # Step 3: Run the tests
              # make migrations
              run: docker-compose run --rm web sh -c "python3 manage.py makemigrations"  # Use Docker Compose to make migrations
              # apply migrations
              run: docker-compose run --rm web sh -c "python3 manage.py migrate"  # Use Docker Compose to apply migrations
              # load test data
              run: docker-compose run --rm web sh -c "python3 manage.py load_geojson.py"  # Use Docker Compose to load test data
              run: docker-compose run --rm web sh -c "python3 manage.py test"  # Use Docker Compose to run the Django unit tests